apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tea.oc.venafi-tpp.riaz-mohamed-gcp.jetstacker.net
  namespace: tea
spec:
  secretName: tea-oc-enafi-tpp.riaz-mohamed-gcp.jetstacker.net
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - tea.oc.venafi-tpp.riaz-mohamed-gcp.jetstacker.net
  #uris:
  #  - spiffe://cluster.local/ns/sandbox/sa/example
  #ipAddresses:
  #  - 192.168.0.5
  commonName: tea.oc.enafi-tpp.riaz-mohamed-gcp.jetstacker.net
  privateKey: 
    rotationPolicy: Always
  #duration: 2160h # 90d
  renewBefore: 360h # 15d
  #subject:
    #organizations:
      #- jetstack
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used. Use these if any policies are enforced on cert creation with TPP
  #commonName: example.com
  #isCA: false
  #privateKey:
    #algorithm: RSA
    #encoding: PKCS1
    #size: 2048
  #usages:
    #- server auth
    #- client auth
  issuerRef:
    name: cluster-venafi-tpp-issuer
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    # group: cert-manager.io