apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: venafi-tpp-demo1-ingress-tea
  namespace: tea
spec:
  tls:
  - hosts:
    - tea.oc.venafi-tpp.REPLACE_DOMAIN_NAME
    secretName: tea-oc-venafi-tpp.REPLACE_DOMAIN_NAME
  rules:
  - host: tea.oc.venafi-tpp.REPLACE_DOMAIN_NAME
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port: 
              number: 80