 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: venafi-tpp-demo1-ingress-coffee
   namespace: coffee
 spec:
   tls:
   - hosts:
     - coffee.oc.venafi-tpp.REPLACE_DOMAIN_NAME
     secretName: coffee-oc-venafi-tpp.REPLACE_DOMAIN_NAME
   rules:
   - host: coffee.oc.venafi-tpp.REPLACE_DOMAIN_NAME
     http:
       paths:
       - path: /coffee
         pathType: Prefix
         backend:
           service:
              name: coffee-svc
              port: 
                number: 80