apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-app-trustore-client
  namespace: truststores
spec:
  secretName: my-app-trustore-secret-client
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - client auth
  commonName: myapp
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io